services:
  frontend:
    platform: linux/arm64/v8  # 또는 배포 서버의 플랫폼에 맞춰 linux/amd64
    image: mrdos89/slivermate-project-react:latest
    container_name: slivermate-container
    ports:
      - "80:80"
    networks:
      - my-network
      
networks:
  my-network:
    external: true # 기존 네트워크에 합류 true

# run
# docker compose --env-file .env up -d

# 서비스 종료
# docker compose down

